services:
  postgres:
    image: postgres:16-alpine
    ports:
      # BEST PRACTICE: Ascultă DOAR pe localhost-ul serverului Debian.
      # DBeaver NU se mai poate conecta direct prin IP, doar prin SSH Tunnel.
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 128M

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Securizat: Doar localhost (Nginx se ocupă de restul)
      - "127.0.0.1:8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    command: ["/app/server"]
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M

  adminer:
    image: adminer
    restart: always
    ports:
      # Aceasta e singura excepție: Îl lăsăm accesibil ca să poți vedea datele din browser
      - "8888:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 64M

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env  
    volumes:
      - ./nginx/secure/:/etc/nginx/templates/
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped
    profiles: ["prod"]
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 32M

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"  
    profiles: ["prod"]
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 32M

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: